server:
  port: 10001

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      nacos:
        enabled=true
    gateway:
      discovery:
        locator:
          enabled: true # 启用自动根据服务ID生成路由
          lower-case-service-id: true # 设置路由的路径为小写的服务ID
      routes:
        - id: nacos-consumer
          uri: lb://service-consumer
          predicates:
            - Path=/nacos-consumer/**
          filters:
            - StripPrefix=1 # 移除前缀 nacos-consumer
        - id: nacos-provider
          uri: lb://service-provider
          predicates:
            - Path=/nacos-provider/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public


